from django.core.management.base import BaseCommand
from tourism.models import Destination

DESTINATIONS = [
    # ─── BAGMATI (Province 3) ───────────────────────────────────────────────
    {
        "name": "Bhaktapur",
        "province": "Bagmati",
        "description": "Bhaktapur, the 'City of Devotees', is a living museum of medieval Newari culture. Its Durbar Square — a UNESCO World Heritage Site — is packed with intricately carved temples, courtly palaces, and artisan workshops unchanged for centuries. Potters still shape clay on wheels in Pottery Square, and the air carries the warm scent of dried chillies drying on ancient brick rooftops.",
        "highlights": ["Bhaktapur Durbar Square", "Nyatapola Temple", "Pottery Square", "Peacock Window", "Dattatreya Temple", "Bhairabnath Temple"],
        "best_time_to_visit": "October to April",
        "latitude": 27.6710,
        "longitude": 85.4298,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Bhaktapur-durbar-square.jpg/1280px-Bhaktapur-durbar-square.jpg",
    },
    {
        "name": "Patan (Lalitpur)",
        "province": "Bagmati",
        "description": "Patan, the 'City of Fine Arts', is the oldest of the Kathmandu Valley's three royal cities. Its Durbar Square is densely packed with stunning Newari architecture — gilded roofs, stone sculptures, and elaborately decorated courtyards. The Patan Museum is among the finest in Asia, and the city's metalwork, thangka painting, and woodcarving traditions remain vibrantly alive.",
        "highlights": ["Patan Durbar Square", "Patan Museum", "Golden Temple", "Kumbeswar Temple", "Kwa Bahal", "Mahaboudha Temple"],
        "best_time_to_visit": "October to May",
        "latitude": 27.6644,
        "longitude": 85.3188,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Patan_Durbar_Square.jpg/1280px-Patan_Durbar_Square.jpg",
    },
    {
        "name": "Boudhanath",
        "province": "Bagmati",
        "description": "Boudhanath Stupa is one of the largest Buddhist stupas in the world and a spiritual heart of Nepal's Tibetan community. The all-seeing eyes of the Buddha gaze from its white dome across a circle of prayer wheels, butter lamps, and maroon-robed monks. Monasteries line every lane, and the evening kora — circumambulation — fills the square with soft chanting and the scent of incense.",
        "highlights": ["Boudhanath Stupa", "Tibetan Monasteries", "Prayer Wheel Circuit", "Thangka Galleries", "Kopan Monastery", "Seto Gumba"],
        "best_time_to_visit": "October to April",
        "latitude": 27.7215,
        "longitude": 85.3620,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Bodnath.jpg/1280px-Bodnath.jpg",
    },
    {
        "name": "Pashupatinath Temple",
        "province": "Bagmati",
        "description": "Pashupatinath is one of the holiest Hindu temples in the world and the most sacred Shiva shrine in Nepal. Set along the Bagmati River, its golden-roofed pagoda, burning ghats, and wandering sadhus create one of the most spiritually intense experiences in South Asia. Hindus believe dying here grants moksha — liberation from the cycle of rebirth.",
        "highlights": ["Main Temple Complex", "Arya Ghat (Cremation Ghats)", "Sadhus of Pashupatinath", "Panch Deval", "Gorakhnath Temple", "Mrigasthali Forest"],
        "best_time_to_visit": "October to March",
        "latitude": 27.7105,
        "longitude": 85.3487,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Pashupatinath_Temple.jpg/1280px-Pashupatinath_Temple.jpg",
    },
    {
        "name": "Swayambhunath (Monkey Temple)",
        "province": "Bagmati",
        "description": "Swayambhunath sits atop a hill west of Kathmandu, its all-seeing eyes watching over the valley from one of the oldest religious sites in Nepal. The approach up 365 steep steps is lined with prayer flags, Buddha statues, and cheeky resident monkeys. Both Hindus and Buddhists worship here, making it a powerful symbol of Nepal's religious harmony.",
        "highlights": ["Main Stupa and Eyes", "365 Steps Climb", "Resident Monkeys", "Dewa Dharma Monastery", "Natural History Museum", "Panoramic Kathmandu View"],
        "best_time_to_visit": "Year round",
        "latitude": 27.7149,
        "longitude": 85.2904,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Swayambhunath-stupa.jpg/1280px-Swayambhunath-stupa.jpg",
    },
    {
        "name": "Nagarkot",
        "province": "Bagmati",
        "description": "Perched at 2,195m on the rim of the Kathmandu Valley, Nagarkot is Nepal's most celebrated sunrise viewpoint. On clear days the entire arc of the Himalayan range — from Dhaulagiri in the west to Kanchenjunga in the east — glows pink at dawn. The surrounding pine forests are perfect for gentle hikes, and the village has a laid-back resort feel a world away from Kathmandu's bustle.",
        "highlights": ["Himalayan Sunrise View", "Kathmandu Valley Panorama", "Nagarkot Hiking Trail", "Tower of Views", "Changu Narayan Day Hike", "Forest Walks"],
        "best_time_to_visit": "October to December, March to April",
        "latitude": 27.7167,
        "longitude": 85.5167,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Nagarkot_sunrise.jpg/1280px-Nagarkot_sunrise.jpg",
    },
    {
        "name": "Langtang Valley",
        "province": "Bagmati",
        "description": "Langtang Valley is the closest major trekking region to Kathmandu — just four hours by road — yet it feels like a different world. The valley cuts deep into the Himalayan foothills through rhododendron forests and yak pastures to the foot of Langtang Lirung (7,227m). Tamang villages with mani walls and prayer flags dot the trail, and the Kyanjin Gompa is a highlight of any Himalayan journey.",
        "highlights": ["Kyanjin Gompa Monastery", "Tserko Ri Viewpoint", "Langtang Lirung View", "Tamang Heritage Trail", "Cheese Factory at Kyanjin", "Gosaikunda Lakes"],
        "best_time_to_visit": "March to May, September to November",
        "latitude": 28.2075,
        "longitude": 85.5139,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Langtang_Valley.jpg/1280px-Langtang_Valley.jpg",
    },
    {
        "name": "Gosaikunda",
        "province": "Bagmati",
        "description": "Gosaikunda is a sacred high-altitude lake at 4,380m, revered by Hindus as the dwelling of Lord Shiva. During the Janai Purnima festival in August, thousands of pilgrims make the arduous journey to bathe in its icy waters and receive blessings. The trail up from Dhunche passes through rhododendron forests and offers stunning views of the Langtang and Ganesh Himal ranges.",
        "highlights": ["Sacred Lake of Lord Shiva", "Janai Purnima Pilgrimage", "Lauribina Pass (4,610m)", "Alpine Flora and Fauna", "Tribal Sacred Circuit", "Panoramic Himalayan Views"],
        "best_time_to_visit": "May to June, September to November",
        "latitude": 28.0833,
        "longitude": 85.4167,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Gosaikunda_lake.jpg/1280px-Gosaikunda_lake.jpg",
    },
    {
        "name": "Dhulikhel",
        "province": "Bagmati",
        "description": "Dhulikhel is a charming hilltop town 30km east of Kathmandu, famous for sweeping Himalayan views and well-preserved Newari architecture. The old bazaar is a relaxed maze of carved windows, courtyard temples, and traditional homes. Easy day hikes lead to ridge-top viewpoints and the hilltop Kali Temple, making it a perfect base for exploring the valley's less-visited eastern corner.",
        "highlights": ["Himalayan Panorama from Main Square", "Old Newari Bazaar", "Namobuddha Hike", "Kali Temple Ridge", "Sunrise Views", "Araniko Highway Scenery"],
        "best_time_to_visit": "October to April",
        "latitude": 27.6213,
        "longitude": 85.5468,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Dhulikhel.jpg/1280px-Dhulikhel.jpg",
    },
    # ─── GANDAKI (Province 4) ──────────────────────────────────────────────
    {
        "name": "Annapurna Base Camp",
        "province": "Gandaki",
        "description": "The Annapurna Base Camp trek leads through lush subtropical forests, past terraced rice paddies, and into the glacier-ringed amphitheatre at 4,130m — a natural mountain stadium surrounded by ten Himalayan giants including Annapurna I (8,091m). The sanctuary feel of the high camp, with mountains towering on all sides, is unlike anywhere else on earth.",
        "highlights": ["Annapurna Sanctuary Amphitheatre", "Sunrise over Annapurna I", "Machhapuchhre (Fishtail Mountain)", "Rhododendron Forests", "Gurung Villages", "Himalayan Hot Springs at Jhinu"],
        "best_time_to_visit": "March to May, September to November",
        "latitude": 28.5317,
        "longitude": 83.8780,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Annapurna_Base_Camp.jpg/1280px-Annapurna_Base_Camp.jpg",
    },
    {
        "name": "Poon Hill (Ghorepani)",
        "province": "Gandaki",
        "description": "Poon Hill at 3,210m offers what many consider the finest Himalayan sunrise view in Nepal — a blazing horizon of fourteen peaks including Annapurna I, Dhaulagiri, Machhapuchhre, and Hiunchuli. The trek from Nayapul through Tikhedhunga and Ulleri takes trekkers through dense rhododendron forests that burst into spectacular bloom in spring. It's the most popular short trek in the Annapurna region.",
        "highlights": ["Himalayan Sunrise from Poon Hill", "Rhododendron Forest in Bloom", "Ghorepani Village", "Annapurna South View", "Dhaulagiri Panorama", "Gurung Culture"],
        "best_time_to_visit": "February to May, September to December",
        "latitude": 28.4000,
        "longitude": 83.7000,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Poon_Hill_sunrise.jpg/1280px-Poon_Hill_sunrise.jpg",
    },
    {
        "name": "Jomsom",
        "province": "Gandaki",
        "description": "Jomsom is the administrative headquarters of Mustang district, sitting in the dramatic Kali Gandaki River gorge — the deepest valley on earth. The town is a hub for trekkers heading to Upper Mustang and Muktinath, and its stark desert landscape, strong afternoon winds, and Thakali cuisine make it unlike anywhere else in Nepal. Nearby apple orchards produce the finest apples in the Himalayas.",
        "highlights": ["Kali Gandaki Gorge", "Nilgiri and Annapurna Views", "Thakali Cuisine and Culture", "Mustang Apple Orchards", "ACAP Visitor Center", "Gateway to Upper Mustang"],
        "best_time_to_visit": "March to November",
        "latitude": 28.7810,
        "longitude": 83.7290,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Jomsom.jpg/1280px-Jomsom.jpg",
    },
    {
        "name": "Muktinath",
        "province": "Gandaki",
        "description": "Muktinath at 3,800m is one of the most sacred pilgrimage sites in Asia, venerated by both Hindus and Buddhists. The temple complex contains the famous eternal flame — a natural gas seep that burns within water — and 108 waterspouts fed by sacred springs. Pilgrims trek or ride horses up from Jomsom, and the dramatic setting beneath the Thorung La pass is unforgettable.",
        "highlights": ["Muktinath Temple Complex", "108 Sacred Water Spouts", "Eternal Flame and Water", "Jwala Mai Shrine", "Ranipauwa Village", "Kali Gandaki Gorge Views"],
        "best_time_to_visit": "April to June, September to November",
        "latitude": 28.8197,
        "longitude": 83.8719,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Muktinath.jpg/1280px-Muktinath.jpg",
    },
    {
        "name": "Tilicho Lake",
        "province": "Gandaki",
        "description": "Tilicho Lake at 4,919m holds the title of highest lake in the world accessible by trail. Ringed by towering cliffs and permanent snow, the vivid turquoise water appears surreal against the stark grey rock. The hike from Manang through the high camp tests stamina but rewards with a landscape of pure, wild grandeur. The frozen lake in winter is especially dramatic.",
        "highlights": ["World's Highest Lake by Trail", "Tilicho Peak (7,134m)", "High-Altitude Desert Landscape", "Serac Ice Formations", "Annapurna Range Views", "High Camp Overnight"],
        "best_time_to_visit": "April to June, September to October",
        "latitude": 28.6833,
        "longitude": 83.8500,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Tilicho_Lake.jpg/1280px-Tilicho_Lake.jpg",
    },
    {
        "name": "Bandipur",
        "province": "Gandaki",
        "description": "Bandipur is a beautifully preserved Newari hilltop town that was once a prosperous trading post on the old Tibet–India route. Its car-free main bazaar is lined with immaculate 18th-century merchant houses, and the ridge-top position delivers sweeping views of the Marsyangdi Valley and the snow-capped Himalayan skyline. The town has reinvented itself as a boutique hill-station destination.",
        "highlights": ["Newari Heritage Bazaar Street", "Himalayan Panorama from Thani Mai", "Siddha Gufa Cave System", "Bindhyabasini Temple", "Sunset from Tundikhel", "Traditional Newari Architecture"],
        "best_time_to_visit": "October to April",
        "latitude": 27.9333,
        "longitude": 84.4167,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Bandipur_Nepal.jpg/1280px-Bandipur_Nepal.jpg",
    },
    {
        "name": "Gorkha",
        "province": "Gandaki",
        "description": "Gorkha is the ancestral home of the Shah dynasty that unified Nepal and birthplace of the legendary Gurkha soldiers. The hilltop Gorkha Durbar fortress, perched high above the town, commands views across the entire Himalayan range from Dhaulagiri to Ganesh Himal on clear days. The town retains a martial, proud character, and the annual Manakamana pilgrimage draws thousands.",
        "highlights": ["Gorkha Durbar Palace and Fort", "Gorakhnath Temple", "Manakamana Temple (Cable Car)", "Panoramic Himalayan Views", "Gurkha Museum", "Tallo Durbar Palace"],
        "best_time_to_visit": "October to April",
        "latitude": 28.0000,
        "longitude": 84.6333,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Gorkha_Durbar.jpg/1280px-Gorkha_Durbar.jpg",
    },
    {
        "name": "Manaslu Circuit",
        "province": "Gandaki",
        "description": "The Manaslu Circuit is considered one of the last great trekking adventures in Nepal — a complete circuit around the world's eighth-highest mountain (8,163m). The trail traverses the Larkya La pass at 5,160m, passes through remote Tibetan-influenced villages, and offers raw, uncrowded wilderness rarely seen on more popular routes. A restricted-area permit is required, keeping it pristine.",
        "highlights": ["Larkya La Pass (5,160m)", "Manaslu North Base Camp", "Tibetan Buddhist Villages", "Birendra Tal Glacial Lake", "Nubri and Tsum Valley Culture", "Remote Himalayan Wilderness"],
        "best_time_to_visit": "March to May, September to November",
        "latitude": 28.5500,
        "longitude": 84.5600,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Manaslu_Circuit.jpg/1280px-Manaslu_Circuit.jpg",
    },
    # ─── KOSHI (Province 1) ───────────────────────────────────────────────
    {
        "name": "Namche Bazaar",
        "province": "Koshi",
        "description": "Namche Bazaar is the gateway town and trading hub of the Khumbu, sitting in a natural horseshoe bowl at 3,440m. Every Saturday morning its busy market draws Sherpa traders, yak herders, and trekkers from across the region. The town has excellent bakeries, gear shops, and the best view of Ama Dablam and the Khumbu giants from the hilltop above.",
        "highlights": ["Saturday Sherpa Market", "Ama Dablam Vista from Ridge", "Everest View Hotel Hike", "National Park Headquarters", "Khumjung Village Day Trip", "Sherpa Culture Museum"],
        "best_time_to_visit": "March to May, September to November",
        "latitude": 27.8069,
        "longitude": 86.7139,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Namche_Bazaar.jpg/1280px-Namche_Bazaar.jpg",
    },
    {
        "name": "Gokyo Lakes",
        "province": "Koshi",
        "description": "The Gokyo Lakes are a chain of six turquoise glacial lakes at over 4,700m, nestled beside the massive Ngozumpa Glacier — the largest glacier in Nepal. Gokyo Ri (5,357m) above the lakes delivers arguably the finest panorama in the entire Himalayas: a 360° sweep of Everest, Lhotse, Makalu, Cho Oyu, and Gyachung Kang. The valley is quieter and less trodden than the Everest Base Camp route.",
        "highlights": ["Gokyo Ri Sunrise Panorama", "Six Sacred Turquoise Lakes", "Ngozumpa Glacier Walk", "Cho Oyu and Everest Views", "Renjo La Pass Crossing", "Scruffy Yak Caravans"],
        "best_time_to_visit": "March to May, October to November",
        "latitude": 27.9633,
        "longitude": 86.6808,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Gokyo_Lake.jpg/1280px-Gokyo_Lake.jpg",
    },
    {
        "name": "Tengboche Monastery",
        "province": "Koshi",
        "description": "Tengboche Monastery at 3,867m is the most revered Tibetan Buddhist monastery in the Khumbu, framed by a jaw-dropping backdrop of Ama Dablam, Everest, Lhotse, and Nuptse. The annual Mani Rimdu festival in October/November fills the courtyard with elaborate masked dances. Hillary and Tenzing received blessings here before their first ascent of Everest in 1953.",
        "highlights": ["Tengboche Gompa Monastery", "Ama Dablam Backdrop", "Mani Rimdu Festival", "Mount Everest View", "Sherpa Sherpa Culture", "Sacred Rhododendron Forest"],
        "best_time_to_visit": "March to May, October to November",
        "latitude": 27.8362,
        "longitude": 86.7640,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Tengboche_Monastery.jpg/1280px-Tengboche_Monastery.jpg",
    },
    {
        "name": "Kanchenjunga Base Camp",
        "province": "Koshi",
        "description": "The Kanchenjunga trek leads to the base of the world's third-highest mountain (8,586m) through pristine forests, terraced farms, and remote Rai and Limbu villages virtually untouched by mass tourism. The north and south base camps offer extraordinary views of Kanchenjunga's massive south face and Yalung Glacier. This restricted, permit-required trek delivers true wilderness adventure.",
        "highlights": ["Kanchenjunga South Base Camp", "Yalung Glacier Moraine", "Rai and Limbu Villages", "Oktang High Camp Views", "Ramthan and Tseram Villages", "Remote Forest Wildlife"],
        "best_time_to_visit": "March to May, October to November",
        "latitude": 27.7025,
        "longitude": 88.1475,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Kanchenjunga.jpg/1280px-Kanchenjunga.jpg",
    },
    {
        "name": "Ilam",
        "province": "Koshi",
        "description": "Ilam is Nepal's premier tea-growing district, tucked into rolling green hills in the far east of the country. The manicured tea gardens produce some of the finest Himalayan teas in the world, and walking among the bushes with the scent of fresh leaves in the air is one of Nepal's most pleasant sensory experiences. The mild climate, waterfalls, and border views into India and Sikkim complete the picture.",
        "highlights": ["Ilam Tea Gardens Walk", "Mai River Valley", "Antu Danda Viewpoint", "Sandakpur Trek Start", "Shree Antu Hill Sunrise", "Local Tea Factory Visit"],
        "best_time_to_visit": "March to May, September to November",
        "latitude": 26.9122,
        "longitude": 87.9244,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Ilam_tea_garden.jpg/1280px-Ilam_tea_garden.jpg",
    },
    {
        "name": "Makalu Base Camp",
        "province": "Koshi",
        "description": "The Makalu Base Camp trek is one of the most demanding and rewarding journeys in Nepal, leading to the foot of the world's fifth-highest mountain (8,485m) through the pristine Arun Valley. The Makalu-Barun Conservation Area shelters one of the most biodiverse corners of the Himalayas, with red pandas, snow leopards, and over 400 bird species. Very few trekkers make it here — true wilderness.",
        "highlights": ["Makalu (8,485m) South Face", "Barun Valley Wilderness", "Makalu-Barun National Park", "Rare Red Panda Habitat", "Hornbein Col Views", "Pristine Alpine Meadows"],
        "best_time_to_visit": "April to May, October to November",
        "latitude": 27.8898,
        "longitude": 87.0922,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Makalu.jpg/1280px-Makalu.jpg",
    },
    # ─── MADHESH (Province 2) ─────────────────────────────────────────────
    {
        "name": "Janakpur",
        "province": "Madhesh",
        "description": "Janakpur is one of Nepal's holiest Hindu cities — the birthplace of Sita Devi and site of her marriage to Lord Ram. The Janaki Mandir, built in the Mughal-Rajput style in 1911, is Nepal's most ornate temple. The city comes spectacularly alive during the Vivah Panchami festival in November/December, when hundreds of thousands of pilgrims reenact the divine wedding with processions, elephants, and devotional music.",
        "highlights": ["Janaki Mandir Temple", "Ram Sita Vivah Panchami Festival", "Dhanushadham Sacred Pools", "Ganga Sagar Lake", "Mithila Painting Art", "Janakpur Women's Development Centre"],
        "best_time_to_visit": "October to March",
        "latitude": 26.7288,
        "longitude": 85.9262,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Janaki_Mandir.jpg/1280px-Janaki_Mandir.jpg",
    },
    {
        "name": "Koshi Tappu Wildlife Reserve",
        "province": "Koshi",
        "description": "Koshi Tappu Wildlife Reserve in the eastern Terai is Nepal's most important wetland, sitting on the Sapt Koshi floodplain and attracting over 500 species of birds — more than the entire United Kingdom. The reserve protects the last remaining population of wild Asian water buffalo (arna) and is a critical stopover for migrating birds on the Central Asian Flyway. Elephant and canoe safaris reveal its rich wildlife up close.",
        "highlights": ["500+ Bird Species Watching", "Wild Water Buffalo (Arna)", "Koshi Barrage River Safari", "Canoe and Elephant Safari", "Gangetic Dolphin Spotting", "Migratory Bird Hotspot"],
        "best_time_to_visit": "October to April",
        "latitude": 26.6333,
        "longitude": 87.0000,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Koshi_Tappu.jpg/1280px-Koshi_Tappu.jpg",
    },
    # ─── LUMBINI (Province 5) ─────────────────────────────────────────────
    {
        "name": "Bardia National Park",
        "province": "Lumbini",
        "description": "Bardia National Park in the western Terai is Nepal's largest national park and its best-kept wildlife secret. Away from Chitwan's crowds, Bardia offers wild tiger tracking, elephant spotting in tall grass, and Gharial crocodile watching along the Karnali River — all in an environment that feels genuinely wild. The Tharu cultural villages surrounding the park add a rich human dimension.",
        "highlights": ["Wild Tiger Tracking on Foot", "Karnali River Boat Safari", "Gharial Crocodile Spotting", "Tharu Cultural Villages", "Elephant Herd Encounters", "Blackbuck Antelope"],
        "best_time_to_visit": "October to April",
        "latitude": 28.3333,
        "longitude": 81.5000,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Bardia_National_Park.jpg/1280px-Bardia_National_Park.jpg",
    },
    {
        "name": "Tansen (Palpa)",
        "province": "Lumbini",
        "description": "Tansen is a perfectly preserved hilltop trading town in Palpa district, its cobblestone alleys lined with the country's finest dhaka-weaving studios and metalwork shops. The panoramic view from Shrinagar Hill takes in the full sweep of the Himalayas from Dhaulagiri to Ganesh Himal, and the historic Rani Mahal palace by the Kali Gandaki river is nicknamed the 'Taj Mahal of Nepal'.",
        "highlights": ["Tansen Durbar Square", "Rani Mahal Palace (Taj Mahal of Nepal)", "Dhaka Fabric Weaving", "Shrinagar Hill Panorama", "Amar Narayan Temple", "Srinagar Hill Sunrise"],
        "best_time_to_visit": "October to April",
        "latitude": 27.8667,
        "longitude": 83.5500,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Tansen_Nepal.jpg/1280px-Tansen_Nepal.jpg",
    },
    {
        "name": "Tilaurakot",
        "province": "Lumbini",
        "description": "Tilaurakot is the ancient capital of the Shakya kingdom and the childhood home of Siddhartha Gautama — the prince who became the Buddha. Archaeological excavations have uncovered the palace ruins, moats, and city gates where young Siddhartha lived for 29 years before renouncing his royal life. The site has a deeply contemplative atmosphere, especially at dawn when pilgrims walk its perimeter in silent meditation.",
        "highlights": ["Ancient Shakya Palace Ruins", "Eastern and Western Gates", "Archaeological Museum", "Sacred Moat and Ramparts", "Kudan Stupa Ruins", "Contemplative Pilgrimage Circuit"],
        "best_time_to_visit": "October to March",
        "latitude": 27.5739,
        "longitude": 83.0511,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Tilaurakot.jpg/1280px-Tilaurakot.jpg",
    },
    {
        "name": "Pokhara Paragliding",
        "province": "Gandaki",
        "description": "Pokhara is the paragliding capital of Asia and one of the world's great tandem paragliding destinations. Launching from Sarangkot (1,592m), pilots and passengers soar in thermals for 30–90 minutes with the entire Annapurna range laid out before them, Phewa Lake glittering below, and Machhapuchhre's perfect pyramid rising to the north. Over 50 licensed companies operate flights year-round in good weather.",
        "highlights": ["Tandem Paragliding from Sarangkot", "Annapurna Range Aerial View", "Phewa Lake from the Air", "Sunrise Paragliding", "World Class Thermal Flying", "Landing at Pokhara Lakeside"],
        "best_time_to_visit": "September to May",
        "latitude": 28.2096,
        "longitude": 83.9856,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Paragliding_Pokhara.jpg/1280px-Paragliding_Pokhara.jpg",
    },
    # ─── KARNALI (Province 6) ─────────────────────────────────────────────
    {
        "name": "Rara Lake",
        "province": "Karnali",
        "description": "Rara Lake is Nepal's largest and deepest lake, a gem of crystalline deep-blue water in the remote Karnali highlands at 2,990m. Ringed by pine and juniper forests, snow-dusted peaks, and the calls of Himalayan black bears and red pandas, it is perhaps the most peaceful and unspoiled place in the entire country. The lack of roads means access is by a short flight to Talcha Airport, making it genuinely off the beaten path.",
        "highlights": ["Largest Lake in Nepal", "Rara National Park", "Crystal Clear Deep Blue Water", "Chuchemara Peak Views", "Red Panda and Bear Habitat", "Pristine Untouched Wilderness"],
        "best_time_to_visit": "April to June, September to November",
        "latitude": 29.5167,
        "longitude": 82.0833,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Rara_Lake.jpg/1280px-Rara_Lake.jpg",
    },
    {
        "name": "Shey Phoksundo Lake",
        "province": "Karnali",
        "description": "Shey Phoksundo is Nepal's deepest lake and the centerpiece of Shey Phoksundo National Park, Nepal's largest protected area. Its ethereal translucent turquoise water — caused by minerals dissolving from limestone — is unlike any other lake in Nepal. The surrounding Dolpo region is the most Tibetan-influenced part of Nepal, and the white-walled Ringmo village on the lake shore feels like a step into Tibet.",
        "highlights": ["Nepal's Deepest Turquoise Lake", "Ringmo Bon Village", "Phoksundo Waterfall", "Snow Leopard Territory", "Bon Religion Gompa", "Upper Dolpo Wilderness Trek"],
        "best_time_to_visit": "May to October",
        "latitude": 29.1194,
        "longitude": 82.9444,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Phoksundo_lake.jpg/1280px-Phoksundo_lake.jpg",
    },
    {
        "name": "Dolpo",
        "province": "Karnali",
        "description": "Dolpo is Nepal's most remote and mysterious trekking destination, an ancient Tibetan-Buddhist kingdom that remained closed to the outside world until 1989. The landscape is stark, windswept, and deeply sacred — stone monasteries cling to cliff faces, sky-blue lakes reflect snowfields, and yak caravans follow trade routes unchanged for a thousand years. Peter Matthiessen immortalized it in 'The Snow Leopard'.",
        "highlights": ["Shey Gompa Ancient Monastery", "Crystal Mountain (Shey)", "Tibetan-Influenced Villages", "Snow Leopard Habitat", "Inner Dolpo Restricted Trek", "Sky Burials and Bon Rituals"],
        "best_time_to_visit": "June to October",
        "latitude": 29.2000,
        "longitude": 83.0000,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Dolpo_Nepal.jpg/1280px-Dolpo_Nepal.jpg",
    },
    {
        "name": "Jumla",
        "province": "Karnali",
        "description": "Jumla is the highland capital of Karnali Province at 2,370m, famous for producing the world's highest-altitude apple orchards and a unique strain of red rice that thrives nowhere else. The town is the starting point for treks to Rara Lake and the Humla region, and the surrounding hills are dotted with ancient Hindu temples that predate Kathmandu's most famous shrines.",
        "highlights": ["Channauta and Tila Temples", "Karnali Apple Orchards", "Gateway to Rara Lake Trek", "Tila River Valley", "High-Altitude Red Rice Fields", "Traditional Jumli Culture"],
        "best_time_to_visit": "April to June, September to October",
        "latitude": 29.2744,
        "longitude": 82.1836,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Jumla_Nepal.jpg/1280px-Jumla_Nepal.jpg",
    },
    # ─── SUDURPASHCHIM (Province 7) ──────────────────────────────────────
    {
        "name": "Shuklaphanta National Park",
        "province": "Sudurpashchim",
        "description": "Shuklaphanta National Park in the far western Terai is Nepal's least-visited national park and one of its finest. The vast open grasslands (phanta) are ideal habitat for the world's largest population of swamp deer (barasingha), and tiger, elephant, and leopard sightings are frequent. The park borders India's Dudhwa National Park, and the transboundary ecosystem is one of South Asia's most important conservation zones.",
        "highlights": ["Swamp Deer (Barasingha) Herds", "Tiger and Leopard Safari", "Open Grassland Landscape", "Rani Tal Lake", "Bird Watching (500+ Species)", "Wild Elephant Herds"],
        "best_time_to_visit": "October to April",
        "latitude": 28.9167,
        "longitude": 80.2833,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Shuklaphanta.jpg/1280px-Shuklaphanta.jpg",
    },
    {
        "name": "Khaptad National Park",
        "province": "Sudurpashchim",
        "description": "Khaptad National Park is a vast plateau at 3,000–3,500m in far western Nepal — a sacred highland that was home to the revered Hindu sage Khaptad Baba. Rolling meadows of wildflowers, forests of oak and rhododendron, and quiet lakes make this one of Nepal's most spiritually serene protected areas. The Tribeni sacred river confluence and Ashram are pilgrimage sites for Hindu devotees from across western Nepal and India.",
        "highlights": ["Khaptad Plateau Meadows", "Tribeni Sacred Confluence", "Khaptad Baba Ashram", "Pristine High-Altitude Forest", "Rare Himalayan Medicinal Plants", "Khaptad Lake"],
        "best_time_to_visit": "April to June, September to November",
        "latitude": 29.3667,
        "longitude": 81.2667,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Khaptad_National_Park.jpg/1280px-Khaptad_National_Park.jpg",
    },
    {
        "name": "Api Himal",
        "province": "Sudurpashchim",
        "description": "Api Himal (7,132m) is the highest peak in far western Nepal and the centerpiece of Api-Nampa Conservation Area, Nepal's newest and least-explored trekking region. The approach passes through Hindu villages, dense subtropical forests, and high alpine zones to reach the glacier below the summit pyramid. Very few trekkers visit, making this one of the last true frontiers of Himalayan exploration.",
        "highlights": ["Api (7,132m) Himalayan Peak", "Api-Nampa Conservation Area", "Darchula Border Town", "Remote Western Himalayan Trek", "Untouched Wilderness", "Traditional Far-Western Culture"],
        "best_time_to_visit": "April to May, October to November",
        "latitude": 30.0000,
        "longitude": 80.9333,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Api_Nepal.jpg/1280px-Api_Nepal.jpg",
    },
    # ─── ADDITIONAL POPULAR / UNIQUE ──────────────────────────────────────
    {
        "name": "Kathmandu Durbar Square",
        "province": "Bagmati",
        "description": "Kathmandu Durbar Square is the ancient royal plaza at the heart of the old city, a UNESCO World Heritage Site packed with palaces, temples, and shrines built between the 12th and 18th centuries. The kumari Ghar (palace of the living goddess), the massive Kasthamandap pavilion, and Taleju Temple define this remarkable space. Street life spills through its courtyards in an unbroken stream of ritual, commerce, and everyday Nepali life.",
        "highlights": ["Kumari Ghar Living Goddess", "Kasthamandap Pavilion", "Taleju Temple", "Hanuman Dhoka Palace Museum", "Jagannath Temple Erotic Carvings", "Old Freak Street (Jhochhen)"],
        "best_time_to_visit": "October to April",
        "latitude": 27.7044,
        "longitude": 85.3065,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Kathmandu_Durbar_Square.jpg/1280px-Kathmandu_Durbar_Square.jpg",
    },
    {
        "name": "Trisuli River Rafting",
        "province": "Bagmati",
        "description": "The Trisuli River is Nepal's most popular whitewater rafting river, easily accessible from Kathmandu and offering exciting Grade III–IV rapids through a beautiful forested gorge. Day trips and two-day overnight river camps along the banks are popular with beginners and intermediate rafters alike. The Trisuli flows through dramatic scenery and is a classic introduction to Nepal's extraordinary adventure sports scene.",
        "highlights": ["Grade III-IV Rapids", "River Camping on Sandy Banks", "Forested Canyon Scenery", "Day and Multi-Day Options", "Easy Kathmandu Access", "Beginner Friendly Rafting"],
        "best_time_to_visit": "September to November, February to June",
        "latitude": 27.9000,
        "longitude": 84.8000,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Trisuli_Rafting.jpg/1280px-Trisuli_Rafting.jpg",
    },
    {
        "name": "Upper Mustang",
        "province": "Gandaki",
        "description": "Upper Mustang is the forbidden kingdom — a Tibetan enclave that remained closed to foreigners until 1992 and still requires a costly special permit. The walled city of Lo Manthang, carved caves of Chhoser, and ancient monasteries of Tsarang preserve a living Tibetan culture that has all but vanished in Tibet itself. The arid, wind-sculpted badlands landscape is unlike anything else in Nepal.",
        "highlights": ["Lo Manthang Walled City", "Chhoser Sky Caves", "Tsarang Dzong Monastery", "Tibetan Kingdom Culture", "Tiji Festival (May)", "Desert Himalayan Landscape"],
        "best_time_to_visit": "April to October",
        "latitude": 29.1833,
        "longitude": 83.9667,
        "image": "https://www.thirdrockadventures.com/assets-back/images/news/upper-mustang.jpgCM3.jpg",
    },
    {
        "name": "Namobuddha",
        "province": "Bagmati",
        "description": "Namobuddha (Namo Buddha) is one of the most sacred Buddhist pilgrimage sites in the world, according to Tibetan tradition the place where a young prince gave his body to feed a starving tigress and her cubs — an act of supreme compassion that led to his becoming the Buddha in a future life. The hilltop stupa and Thrangu Tashi Yangtse Monastery make it a profoundly peaceful destination just 40km from Kathmandu.",
        "highlights": ["Namobuddha Sacred Stupa", "Thrangu Tashi Yangtse Monastery", "Legend of the Compassionate Prince", "Valley Views from Hilltop", "Panauti Town Nearby", "Dhulikhel Day Hike Circuit"],
        "best_time_to_visit": "October to May",
        "latitude": 27.5753,
        "longitude": 85.5081,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Namobuddha_Stupa.jpg/1280px-Namobuddha_Stupa.jpg",
    },
    {
        "name": "Helambu",
        "province": "Bagmati",
        "description": "The Helambu region north of Kathmandu offers a gentle introduction to trekking in Nepal through Hyolmo Sherpa villages and lush forest, without the altitude or commitment of the great Himalayan treks. The circuit passes through apple orchards, mani walls, small gompas, and ridge viewpoints with clear views of the Langtang range. It can be done without a guide and is perfect for first-time trekkers.",
        "highlights": ["Hyolmo Sherpa Villages", "Melamchi Gaon View", "Tarke Ghyang Monastery", "Apple Orchard Country", "Easy Kathmandu Access", "Beginner Friendly Trek"],
        "best_time_to_visit": "October to May",
        "latitude": 27.9500,
        "longitude": 85.5500,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Helambu_Trek.jpg/1280px-Helambu_Trek.jpg",
    },
]


class Command(BaseCommand):
    help = "Seed Nepal destinations database with comprehensive data"

    def add_arguments(self, parser):
        parser.add_argument('--skip-existing', action='store_true', help='Skip destinations that already exist by name')

    def handle(self, *args, **options):
        skip_existing = options['skip_existing']
        existing_names = set(Destination.objects.values_list('name', flat=True))
        created = 0
        skipped = 0

        for data in DESTINATIONS:
            name = data['name']
            if skip_existing and name in existing_names:
                self.stdout.write(f"  SKIP  {name}")
                skipped += 1
                continue

            Destination.objects.update_or_create(
                name=name,
                defaults={
                    'province': data['province'],
                    'description': data['description'],
                    'highlights': data['highlights'],
                    'best_time_to_visit': data['best_time_to_visit'],
                    'latitude': data.get('latitude'),
                    'longitude': data.get('longitude'),
                    'image': data.get('image', ''),
                    'is_active': True,
                }
            )
            created += 1
            self.stdout.write(self.style.SUCCESS(f"  OK    {name} ({data['province']})"))

        self.stdout.write(self.style.SUCCESS(
            f"\nDone — {created} destinations added/updated, {skipped} skipped."
        ))
