# Generated by Django 5.2 on 2026-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_image_file_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.URLField(blank=True, default='', help_text='External URL of the main destination image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.URLField(blank=True, default='', help_text='External URL of the hotel image'),
        ),
    ]
