# Generated by Django 5.2 on 2026-05-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_package_enhanced_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at']},
        ),
    ]
