# Generated by Django 5.2 on 2026-05-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('villa', 'Villa'), ('resort', 'Resort'), ('homestay', 'Homestay')], default='hotel', max_length=20),
        ),
    ]
