# Generated by Django 5.2 on 2026-05-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_hotel_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
